/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.kkp.myapp.views;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author titan
 */
public class MainMenu extends javax.swing.JFrame {

    /** Creates new form MainMenu */
    public MainMenu() {
        initComponents();
        this.imagePanel1.setImage("/com/kkp/myapp/assets/aseanindo.png");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMasterKlien = new javax.swing.JButton();
        btnMasterKandidat = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnFormPermintaanKlien = new javax.swing.JButton();
        btnFormInputKandidat = new javax.swing.JButton();
        btnSysUsers = new javax.swing.JButton();
        btnInterview = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        imagePanel1 = new com.kkp.myapp.views.controls.ImagePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuClose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Administrasi Calon Karyawan PT Aseanindo Networks Solutions");
        setAlwaysOnTop(true);
        setResizable(false);

        btnMasterKlien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kkp/myapp/assets/cabinet.png"))); // NOI18N
        btnMasterKlien.setText("Data Klien");
        btnMasterKlien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMasterKlien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnMasterKandidat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kkp/myapp/assets/cabinet.png"))); // NOI18N
        btnMasterKandidat.setText("Data Kandidat");
        btnMasterKandidat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMasterKandidat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kkp/myapp/assets/chart.png"))); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaporan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnFormPermintaanKlien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kkp/myapp/assets/documents.png"))); // NOI18N
        btnFormPermintaanKlien.setText("Form Permintaan Klien");
        btnFormPermintaanKlien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFormPermintaanKlien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnFormInputKandidat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kkp/myapp/assets/documents.png"))); // NOI18N
        btnFormInputKandidat.setText("Form Input Kandidat");
        btnFormInputKandidat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFormInputKandidat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFormInputKandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormInputKandidatActionPerformed(evt);
            }
        });

        btnSysUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kkp/myapp/assets/users.png"))); // NOI18N
        btnSysUsers.setText("Pengguna Sistem");
        btnSysUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSysUsers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnInterview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kkp/myapp/assets/checklist.png"))); // NOI18N
        btnInterview.setText("Interview Kandidat");
        btnInterview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInterview.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kkp/myapp/assets/logout.png"))); // NOI18N
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setLabel("Keluar");
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jMenu1.setText("Master");

        jMenuItem1.setText("Master Pengguna");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Master Alasan Pemberhentian");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Master Alasan Penolakan");
        jMenu1.add(jMenuItem3);

        jMenuItem9.setText("Master Posisi Pekerjaan");
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");

        jMenuItem4.setText("Form Input Data Calon Karyawan");
        jMenu2.add(jMenuItem4);

        jMenuItem7.setText("Form Penerimaan Calon Karyawan");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Form Penghentian Karyawan");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        jMenuItem10.setText("Laporan Data Karyawan");
        jMenu3.add(jMenuItem10);

        jMenuItem5.setText("Laporan Penerimaan Calon Karyawan");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Laporan Pemberhentian Karyawan");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        menuClose.setText("Tutup");
        menuClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCloseMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuClose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMasterKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMasterKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFormInputKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFormPermintaanKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInterview, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSysUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMasterKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMasterKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFormInputKandidat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFormPermintaanKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInterview, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSysUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeApplication() {
        var confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menutup Aplikasi?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        // 0 - Yes
        if (confirm == 0) {
            this.setVisible(false);
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }
    
    private void btnFormInputKandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormInputKandidatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFormInputKandidatActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        closeApplication();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void menuCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCloseMouseClicked
        closeApplication();
    }//GEN-LAST:event_menuCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFormInputKandidat;
    private javax.swing.JButton btnFormPermintaanKlien;
    private javax.swing.JButton btnInterview;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMasterKandidat;
    private javax.swing.JButton btnMasterKlien;
    private javax.swing.JButton btnSysUsers;
    private com.kkp.myapp.views.controls.ImagePanel imagePanel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuClose;
    // End of variables declaration//GEN-END:variables

}
